# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentManager < Formula
  desc "Terminal UI to manage AI coding-agent tmux sessions"
  homepage "https://github.com/YoanWai/agent-manager"
  version "0.5.0"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YoanWai/agent-manager/releases/download/v0.5.0/agent-manager_0.5.0_darwin_amd64.tar.gz"
      sha256 "b1c18e4da1c1531096a75d8fea6d6ee5eb7ef9260f8e48b1329de3ae6e7e773a"

      define_method(:install) do
        bin.install "agent-manager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YoanWai/agent-manager/releases/download/v0.5.0/agent-manager_0.5.0_darwin_arm64.tar.gz"
      sha256 "ad9938052b14b51c07a42f1f7d8d41e766464d87b68359284eb8089ce7ee999e"

      define_method(:install) do
        bin.install "agent-manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YoanWai/agent-manager/releases/download/v0.5.0/agent-manager_0.5.0_linux_amd64.tar.gz"
      sha256 "570e33563d8a53e932ec172c8b0b3fd0f150554ca048d630bd0d8aa372db19b5"
      define_method(:install) do
        bin.install "agent-manager"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YoanWai/agent-manager/releases/download/v0.5.0/agent-manager_0.5.0_linux_arm64.tar.gz"
      sha256 "2e43fa50cc9dfa09537af441e346806be38b2a076a6ac63c91a25386cd556763"
      define_method(:install) do
        bin.install "agent-manager"
      end
    end
  end

  test do
    system "#{bin}/agent-manager", "--version"
  end
end
