# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentManager < Formula
  desc "Terminal UI to manage AI coding-agent tmux sessions"
  homepage "https://github.com/YoanWai/agent-manager"
  version "0.1.0"
  license "AGPL-3.0-only"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YoanWai/agent-manager/releases/download/v0.1.0/agent-manager_0.1.0_darwin_amd64.tar.gz"
      sha256 "08ec7bae57910dde8a193cf89d5a0ee5ce27872a757d282a3660d96aab9627cf"

      define_method(:install) do
        bin.install "agent-manager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YoanWai/agent-manager/releases/download/v0.1.0/agent-manager_0.1.0_darwin_arm64.tar.gz"
      sha256 "36e844a75eab657020e470797ccb2270f5df1b92243d40f91b92c96cde5d3122"

      define_method(:install) do
        bin.install "agent-manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YoanWai/agent-manager/releases/download/v0.1.0/agent-manager_0.1.0_linux_amd64.tar.gz"
      sha256 "68e97d4b3b004561f397fcb846af08da0c09fb967dd6d5953b864dc75f13084e"
      define_method(:install) do
        bin.install "agent-manager"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YoanWai/agent-manager/releases/download/v0.1.0/agent-manager_0.1.0_linux_arm64.tar.gz"
      sha256 "aee2c7c7c5a65c1f72d757a9ab626aef9f602c2349c5e2e2cccc8f94bbba8f51"
      define_method(:install) do
        bin.install "agent-manager"
      end
    end
  end

  test do
    system "#{bin}/agent-manager", "--version"
  end
end
