# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-manager" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/agent-manager"]
    end
  end

  version "0.41.0"

  on_macos do
    on_arm do
      sha256 "7186f9b40af485468a855085fb44a16221496a33300304c799a6a3d0ee8d99ea"
      url "https://github.com/YoanWai/agent-manager/releases/download/v#{version}/agent-manager_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fe03239f514d4cc35a3ebb69b227ad5e947970faf1110bc0c9b9f8012d1e6015"
      url "https://github.com/YoanWai/agent-manager/releases/download/v#{version}/agent-manager_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "312bd67f035edc30ba849eb48b48b11a91ef4ac6f0ac1bfbf501bb2ba5fc8f91"
      url "https://github.com/YoanWai/agent-manager/releases/download/v#{version}/agent-manager_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5ec6dc1ba0f5715881d0c5ac163f79b6a1843e2ab7ce6bbbcc34f95533e2a9d"
      url "https://github.com/YoanWai/agent-manager/releases/download/v#{version}/agent-manager_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agent-manager"
  desc "Run Claude Code, Codex, OpenCode and other AI coding agents in tmux"
  homepage "https://agent-manager.dev/"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "agent-manager"

  # No zap stanza required
end
