# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-manager" do
  version "0.25.0"

  on_macos do
    on_intel do
      sha256 "5498f3a3e648666e61e6f0dc5f690a01b1346def40750e18f9ff0c9bb3effb58"
      url "https://github.com/YoanWai/agent-manager/releases/download/v#{version}/agent-manager_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "51922655b274bd94007a893a5470963f2b93b52d7cb8cfb0456a665821c6b27e"
      url "https://github.com/YoanWai/agent-manager/releases/download/v#{version}/agent-manager_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d3922331ec25b24b748dbb10edb4c361f33ccc038ae7e55547a3f2d61fbd9c31"
      url "https://github.com/YoanWai/agent-manager/releases/download/v#{version}/agent-manager_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab54f28bb6fdda69833a1d89fd4c70a196a2b6b2fa09bf1b5fe4717c8eb59d92"
      url "https://github.com/YoanWai/agent-manager/releases/download/v#{version}/agent-manager_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agent-manager"
  desc "Terminal UI to manage AI coding-agent tmux sessions"
  homepage "https://github.com/YoanWai/agent-manager"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "agent-manager"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agent-manager"]
    end
  end

  # No zap stanza required

end
