# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-manager" do
  version "0.35.0"

  on_macos do
    on_intel do
      sha256 "6bd5db5d2bf57fc2a237e6cf104fb12a4bb61e104ff9acea4c98658372df7616"
      url "https://github.com/YoanWai/agent-manager/releases/download/v#{version}/agent-manager_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7ffcd31b4f6ef6e10fa6e2f616fb6d1b40fb38b524b981fdd75d335ad3550b49"
      url "https://github.com/YoanWai/agent-manager/releases/download/v#{version}/agent-manager_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef6fa3e974e474725a22dd2aa15dc8ff4e2fc0ab25637582e1f06186e0d65545"
      url "https://github.com/YoanWai/agent-manager/releases/download/v#{version}/agent-manager_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "298f32da4aa762d5d047e39c0671f71e78017f0da1ccf1060d1de5d4dbedd322"
      url "https://github.com/YoanWai/agent-manager/releases/download/v#{version}/agent-manager_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agent-manager"
  desc "Terminal UI to manage AI coding-agent tmux sessions"
  homepage "https://github.com/YoanWai/agent-manager"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "agent-manager"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agent-manager"]
    end
  end

  # No zap stanza required

end
